package shaper.mapping.model.shacl;

import janus.database.DBSchema;
import shaper.Shaper;
import shaper.mapping.Symbols;
import shaper.mapping.model.r2rml.R2RMLModel;

import java.net.URI;
import java.util.Map;
import java.util.Set;

public class ShaclDocModelFactory {
    // R2RML
    public static ShaclDocModel getSHACLDocModel(R2RMLModel r2rmlModel) {
        ShaclDocModel shaclDocModel = new ShaclDocModel(URI.create(Shaper.shapeBaseURI), Shaper.prefixForShapeBaseURI);

        // directives
        // IMPORTS: impossible since the RDF graph generated by r2rml-parser doesn't declare @base directive.
        // ;

        // PREFIX: from RDF graph generated by the R2RML document.
        Set<Map.Entry<String, String>> entrySet = r2rmlModel.getPrefixMap().entrySet();
        for (Map.Entry<String, String> entry: entrySet)
            shaclDocModel.addPrefixDecl(entry.getKey(), entry.getValue());

        return shaclDocModel;
    }

    //Direct Mapping
    public static ShaclDocModel getSHACLDocModel(DBSchema dbSchema) {
        return null;
    }
}
